params:
  determinist: True
  pop_size: 10000
  sel_coeff_shape: -1
  b_cold: 6e-6
  dominance_coeff: 0.5
  nb_sim: 1e6
scale:
  b_hot:
    min: 6e-6
    max: 0.02
    steps: 10
  sel_coeff:
    min: 6e-6
    max: 0.02
    steps: 10
  lifespan: [0.1, 0.5, 1.0, 2, 4, 8]